import { DM_Sans, Urbanist, Inter } from "next/font/google";
import "../app/globals.css";
import Providers from '../Providers/Providers'
import { AntdRegistry } from "@ant-design/nextjs-registry";

// Import fonts
const dmSans = DM_Sans({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-dm-sans" });
const urbanist = Urbanist({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-urbanist" });
const inter = Inter({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Kevin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${urbanist.variable} ${inter.variable} antialiased bg-[#EAECEE]`}
      >
        <Providers>
        <AntdRegistry>{children}</AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
